services:
  myapp:
    build: .
    container_name: registration
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9091:8080"
    networks:
      - hackaton_net

  db:
    image: postgres:16.2
    shm_size: 1g
    container_name: userservice_psql
    restart: always
    environment:
      - POSTGRES_USER=userservice
      - POSTGRES_PASSWORD=P0o9i8u7
      - POSTGRES_DB=user_service
    ports:
      - '5433:5432'
    volumes:
      - dbdata_userservice:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - hackaton_net

volumes:
  dbdata_userservice:

networks:
  hackaton_net:
    name: hackaton_net
    external: true