server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: userservice
    password: P0o9i8u7
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
springdoc:
    swagger-ui:
        path: /swagger-ui/index.html
        
jwt:
  secret: "z8kL7#pX$5vN@qR9!tB2mY4wG6jD1hF3eC5sJ7uK9xM0lO4iP8vQ2aZ5rT6yU"
  expiration: 86400000